apiVersion: apps/v1
kind: Deployment
metadata:
  name: baro-kafka-consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baro-kafka-consumer
  template:
    metadata:
      labels:
        app: baro-kafka-consumer
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-master
      hostAliases:
        - ip: "10.20.10.31"
          hostnames:
            - "kafka.baro.internal"
      containers:
        - name: baro-kafka-consumer
          image: docker.io/library/baro-kafka-consumer:latest
          imagePullPolicy: Never
          env:
            - name: TIMESCALEDB_CONSUMER_ENABLED
              value: "true"
            - name: GEO_CONSUMER_ENABLED
              value: "false"
          envFrom:
            - secretRef:
                name: baro-kafka-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
